(cl:defpackage jerky_mov-msg
  (:use )
  (:export
   "<MOVE_ARM_JOINTSGOAL>"
   "MOVE_ARM_JOINTSGOAL"
   "<MOVE_ARM_JOINTSACTION>"
   "MOVE_ARM_JOINTSACTION"
   "<MOVE_ARM_JOINTSACTIONRESULT>"
   "MOVE_ARM_JOINTSACTIONRESULT"
   "<MOVE_ARM_JOINTSACTIONGOAL>"
   "MOVE_ARM_JOINTSACTIONGOAL"
   "<MOVE_ARM_JOINTSRESULT>"
   "MOVE_ARM_JOINTSRESULT"
   "<MOVE_ARM_JOINTSACTIONFEEDBACK>"
   "MOVE_ARM_JOINTSACTIONFEEDBACK"
   "<MOVE_ARM_JOINTSFEEDBACK>"
   "MOVE_ARM_JOINTSFEEDBACK"
  ))

