; Auto-generated. Do not edit!


(cl:in-package jerky_mov-msg)


;//! \htmlinclude move_arm_jointsFeedback.msg.html

(cl:defclass <move_arm_jointsFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass move_arm_jointsFeedback (<move_arm_jointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <move_arm_jointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'move_arm_jointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jerky_mov-msg:<move_arm_jointsFeedback> is deprecated: use jerky_mov-msg:move_arm_jointsFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <move_arm_jointsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jerky_mov-msg:percent_complete-val is deprecated.  Use jerky_mov-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <move_arm_jointsFeedback>) ostream)
  "Serializes a message object of type '<move_arm_jointsFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <move_arm_jointsFeedback>) istream)
  "Deserializes a message object of type '<move_arm_jointsFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<move_arm_jointsFeedback>)))
  "Returns string type for a message object of type '<move_arm_jointsFeedback>"
  "jerky_mov/move_arm_jointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'move_arm_jointsFeedback)))
  "Returns string type for a message object of type 'move_arm_jointsFeedback"
  "jerky_mov/move_arm_jointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<move_arm_jointsFeedback>)))
  "Returns md5sum for a message object of type '<move_arm_jointsFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'move_arm_jointsFeedback)))
  "Returns md5sum for a message object of type 'move_arm_jointsFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<move_arm_jointsFeedback>)))
  "Returns full string definition for message of type '<move_arm_jointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'move_arm_jointsFeedback)))
  "Returns full string definition for message of type 'move_arm_jointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <move_arm_jointsFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <move_arm_jointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'move_arm_jointsFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
