; Auto-generated. Do not edit!


(cl:in-package jerky_mov-msg)


;//! \htmlinclude move_arm_jointsResult.msg.html

(cl:defclass <move_arm_jointsResult> (roslisp-msg-protocol:ros-message)
  ((complete
    :reader complete
    :initarg :complete
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass move_arm_jointsResult (<move_arm_jointsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <move_arm_jointsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'move_arm_jointsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jerky_mov-msg:<move_arm_jointsResult> is deprecated: use jerky_mov-msg:move_arm_jointsResult instead.")))

(cl:ensure-generic-function 'complete-val :lambda-list '(m))
(cl:defmethod complete-val ((m <move_arm_jointsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jerky_mov-msg:complete-val is deprecated.  Use jerky_mov-msg:complete instead.")
  (complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <move_arm_jointsResult>) ostream)
  "Serializes a message object of type '<move_arm_jointsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'complete) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <move_arm_jointsResult>) istream)
  "Deserializes a message object of type '<move_arm_jointsResult>"
    (cl:setf (cl:slot-value msg 'complete) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<move_arm_jointsResult>)))
  "Returns string type for a message object of type '<move_arm_jointsResult>"
  "jerky_mov/move_arm_jointsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'move_arm_jointsResult)))
  "Returns string type for a message object of type 'move_arm_jointsResult"
  "jerky_mov/move_arm_jointsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<move_arm_jointsResult>)))
  "Returns md5sum for a message object of type '<move_arm_jointsResult>"
  "9d8061d2347621a6ed88451e28811cc7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'move_arm_jointsResult)))
  "Returns md5sum for a message object of type 'move_arm_jointsResult"
  "9d8061d2347621a6ed88451e28811cc7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<move_arm_jointsResult>)))
  "Returns full string definition for message of type '<move_arm_jointsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'move_arm_jointsResult)))
  "Returns full string definition for message of type 'move_arm_jointsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <move_arm_jointsResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <move_arm_jointsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'move_arm_jointsResult
    (cl:cons ':complete (complete msg))
))
