//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the jerky_mov package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __jerky_mov__ARMCONFIG_H__
#define __jerky_mov__ARMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace jerky_mov
{
  class armConfigStatics;
  
  class armConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(armConfig &config, const armConfig &max, const armConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const armConfig &config1, const armConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, armConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const armConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, armConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const armConfig &config) const = 0;
      virtual void getValue(const armConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T armConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (armConfig::* field);

      virtual void clamp(armConfig &config, const armConfig &max, const armConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const armConfig &config1, const armConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, armConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const armConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, armConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const armConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const armConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, armConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, armConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<armConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(armConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("left_s0_p"==(*_i)->name){left_s0_p = boost::any_cast<double>(val);}
        if("left_s1_p"==(*_i)->name){left_s1_p = boost::any_cast<double>(val);}
        if("left_e0_p"==(*_i)->name){left_e0_p = boost::any_cast<double>(val);}
        if("left_e1_p"==(*_i)->name){left_e1_p = boost::any_cast<double>(val);}
        if("left_w0_p"==(*_i)->name){left_w0_p = boost::any_cast<double>(val);}
        if("left_w1_p"==(*_i)->name){left_w1_p = boost::any_cast<double>(val);}
        if("left_w2_p"==(*_i)->name){left_w2_p = boost::any_cast<double>(val);}
        if("right_s0_p"==(*_i)->name){right_s0_p = boost::any_cast<double>(val);}
        if("right_s1_p"==(*_i)->name){right_s1_p = boost::any_cast<double>(val);}
        if("right_e0_p"==(*_i)->name){right_e0_p = boost::any_cast<double>(val);}
        if("right_e1_p"==(*_i)->name){right_e1_p = boost::any_cast<double>(val);}
        if("right_w0_p"==(*_i)->name){right_w0_p = boost::any_cast<double>(val);}
        if("right_w1_p"==(*_i)->name){right_w1_p = boost::any_cast<double>(val);}
        if("right_w2_p"==(*_i)->name){right_w2_p = boost::any_cast<double>(val);}
        if("left_s0_d"==(*_i)->name){left_s0_d = boost::any_cast<double>(val);}
        if("left_s1_d"==(*_i)->name){left_s1_d = boost::any_cast<double>(val);}
        if("left_e0_d"==(*_i)->name){left_e0_d = boost::any_cast<double>(val);}
        if("left_e1_d"==(*_i)->name){left_e1_d = boost::any_cast<double>(val);}
        if("left_w0_d"==(*_i)->name){left_w0_d = boost::any_cast<double>(val);}
        if("left_w1_d"==(*_i)->name){left_w1_d = boost::any_cast<double>(val);}
        if("left_w2_d"==(*_i)->name){left_w2_d = boost::any_cast<double>(val);}
        if("right_s0_d"==(*_i)->name){right_s0_d = boost::any_cast<double>(val);}
        if("right_s1_d"==(*_i)->name){right_s1_d = boost::any_cast<double>(val);}
        if("right_e0_d"==(*_i)->name){right_e0_d = boost::any_cast<double>(val);}
        if("right_e1_d"==(*_i)->name){right_e1_d = boost::any_cast<double>(val);}
        if("right_w0_d"==(*_i)->name){right_w0_d = boost::any_cast<double>(val);}
        if("right_w1_d"==(*_i)->name){right_w1_d = boost::any_cast<double>(val);}
        if("right_w2_d"==(*_i)->name){right_w2_d = boost::any_cast<double>(val);}
        if("left_s0_i"==(*_i)->name){left_s0_i = boost::any_cast<double>(val);}
        if("left_s1_i"==(*_i)->name){left_s1_i = boost::any_cast<double>(val);}
        if("left_e0_i"==(*_i)->name){left_e0_i = boost::any_cast<double>(val);}
        if("left_e1_i"==(*_i)->name){left_e1_i = boost::any_cast<double>(val);}
        if("left_w0_i"==(*_i)->name){left_w0_i = boost::any_cast<double>(val);}
        if("left_w1_i"==(*_i)->name){left_w1_i = boost::any_cast<double>(val);}
        if("left_w2_i"==(*_i)->name){left_w2_i = boost::any_cast<double>(val);}
        if("right_s0_i"==(*_i)->name){right_s0_i = boost::any_cast<double>(val);}
        if("right_s1_i"==(*_i)->name){right_s1_i = boost::any_cast<double>(val);}
        if("right_e0_i"==(*_i)->name){right_e0_i = boost::any_cast<double>(val);}
        if("right_e1_i"==(*_i)->name){right_e1_i = boost::any_cast<double>(val);}
        if("right_w0_i"==(*_i)->name){right_w0_i = boost::any_cast<double>(val);}
        if("right_w1_i"==(*_i)->name){right_w1_i = boost::any_cast<double>(val);}
        if("right_w2_i"==(*_i)->name){right_w2_i = boost::any_cast<double>(val);}
      }
    }

    double left_s0_p;
double left_s1_p;
double left_e0_p;
double left_e1_p;
double left_w0_p;
double left_w1_p;
double left_w2_p;
double right_s0_p;
double right_s1_p;
double right_e0_p;
double right_e1_p;
double right_w0_p;
double right_w1_p;
double right_w2_p;
double left_s0_d;
double left_s1_d;
double left_e0_d;
double left_e1_d;
double left_w0_d;
double left_w1_d;
double left_w2_d;
double right_s0_d;
double right_s1_d;
double right_e0_d;
double right_e1_d;
double right_w0_d;
double right_w1_d;
double right_w2_d;
double left_s0_i;
double left_s1_i;
double left_e0_i;
double left_e1_i;
double left_w0_i;
double left_w1_i;
double left_w2_i;
double right_s0_i;
double right_s1_i;
double right_e0_i;
double right_e1_i;
double right_w0_i;
double right_w1_i;
double right_w2_i;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w2_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w0_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w1_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w2_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w2_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w0_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w1_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w2_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w2_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w0_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w1_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w2_i;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("armConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const armConfig &__max__ = __getMax__();
      const armConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const armConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const armConfig &__getDefault__();
    static const armConfig &__getMax__();
    static const armConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const armConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void armConfig::ParamDescription<std::string>::clamp(armConfig &config, const armConfig &max, const armConfig &min) const
  {
    return;
  }

  class armConfigStatics
  {
    friend class armConfig;
    
    armConfigStatics()
    {
armConfig::GroupDescription<armConfig::DEFAULT, armConfig> Default("Default", "", 0, 0, true, &armConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s0_p = 25.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_p", "double", 0, "proportional term for s0", "", &armConfig::left_s0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_p", "double", 0, "proportional term for s0", "", &armConfig::left_s0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s1_p = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_p", "double", 0, "proportional term for s1", "", &armConfig::left_s1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_p", "double", 0, "proportional term for s1", "", &armConfig::left_s1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e0_p = 40.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_p", "double", 0, "proportional term for e0", "", &armConfig::left_e0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_p", "double", 0, "proportional term for e0", "", &armConfig::left_e0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e1_p = 24.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_p", "double", 0, "proportional term for e1", "", &armConfig::left_e1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_p", "double", 0, "proportional term for e1", "", &armConfig::left_e1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w0_p = 7.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_p", "double", 0, "proportional term for w0", "", &armConfig::left_w0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_p", "double", 0, "proportional term for w0", "", &armConfig::left_w0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w1_p = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_p", "double", 0, "proportional term for w1", "", &armConfig::left_w1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_p", "double", 0, "proportional term for w1", "", &armConfig::left_w1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w2_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w2_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w2_p = 2.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_p", "double", 0, "proportional term for w2", "", &armConfig::left_w2_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_p", "double", 0, "proportional term for w2", "", &armConfig::left_w2_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s0_p = 25.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_p", "double", 0, "proportional term for s0", "", &armConfig::right_s0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_p", "double", 0, "proportional term for s0", "", &armConfig::right_s0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s1_p = 60.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_p", "double", 0, "proportional term for s1", "", &armConfig::right_s1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_p", "double", 0, "proportional term for s1", "", &armConfig::right_s1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e0_p = 40.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_p", "double", 0, "proportional term for e0", "", &armConfig::right_e0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_p", "double", 0, "proportional term for e0", "", &armConfig::right_e0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e1_p = 24.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_p", "double", 0, "proportional term for e1", "", &armConfig::right_e1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_p", "double", 0, "proportional term for e1", "", &armConfig::right_e1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w0_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w0_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w0_p = 7.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_p", "double", 0, "proportional term for w0", "", &armConfig::right_w0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_p", "double", 0, "proportional term for w0", "", &armConfig::right_w0_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w1_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w1_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w1_p = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_p", "double", 0, "proportional term for w1", "", &armConfig::right_w1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_p", "double", 0, "proportional term for w1", "", &armConfig::right_w1_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w2_p = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w2_p = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w2_p = 2.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_p", "double", 0, "proportional term for w2", "", &armConfig::right_w2_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_p", "double", 0, "proportional term for w2", "", &armConfig::right_w2_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s0_d = 8.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_d", "double", 0, "derivative term for s0", "", &armConfig::left_s0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_d", "double", 0, "derivative term for s0", "", &armConfig::left_s0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s1_d = 7.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_d", "double", 0, "derivative term for s1", "", &armConfig::left_s1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_d", "double", 0, "derivative term for s1", "", &armConfig::left_s1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e0_d = 3.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_d", "double", 0, "derivative term for e0", "", &armConfig::left_e0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_d", "double", 0, "derivative term for e0", "", &armConfig::left_e0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e1_d = 3.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_d", "double", 0, "derivative term for e1", "", &armConfig::left_e1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_d", "double", 0, "derivative term for e1", "", &armConfig::left_e1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w0_d = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_d", "double", 0, "derivative term for w0", "", &armConfig::left_w0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_d", "double", 0, "derivative term for w0", "", &armConfig::left_w0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w1_d = 0.8;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_d", "double", 0, "derivative term for w1", "", &armConfig::left_w1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_d", "double", 0, "derivative term for w1", "", &armConfig::left_w1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w2_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w2_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w2_d = 0.4;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_d", "double", 0, "derivative term for w2", "", &armConfig::left_w2_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_d", "double", 0, "derivative term for w2", "", &armConfig::left_w2_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s0_d = 8.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_d", "double", 0, "derivative term for s0", "", &armConfig::right_s0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_d", "double", 0, "derivative term for s0", "", &armConfig::right_s0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s1_d = 7.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_d", "double", 0, "derivative term for s1", "", &armConfig::right_s1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_d", "double", 0, "derivative term for s1", "", &armConfig::right_s1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e0_d = 3.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_d", "double", 0, "derivative term for e0", "", &armConfig::right_e0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_d", "double", 0, "derivative term for e0", "", &armConfig::right_e0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e1_d = 3.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_d", "double", 0, "derivative term for e1", "", &armConfig::right_e1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_d", "double", 0, "derivative term for e1", "", &armConfig::right_e1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w0_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w0_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w0_d = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_d", "double", 0, "derivative term for w0", "", &armConfig::right_w0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_d", "double", 0, "derivative term for w0", "", &armConfig::right_w0_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w1_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w1_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w1_d = 0.8;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_d", "double", 0, "derivative term for w1", "", &armConfig::right_w1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_d", "double", 0, "derivative term for w1", "", &armConfig::right_w1_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w2_d = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w2_d = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w2_d = 0.4;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_d", "double", 0, "derivative term for w2", "", &armConfig::right_w2_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_d", "double", 0, "derivative term for w2", "", &armConfig::right_w2_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s0_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_i", "double", 0, "integral term for s0", "", &armConfig::left_s0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s0_i", "double", 0, "integral term for s0", "", &armConfig::left_s0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s1_i = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_i", "double", 0, "integral term for s1", "", &armConfig::left_s1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_s1_i", "double", 0, "integral term for s1", "", &armConfig::left_s1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e0_i = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_i", "double", 0, "integral term for e0", "", &armConfig::left_e0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e0_i", "double", 0, "integral term for e0", "", &armConfig::left_e0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e1_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_i", "double", 0, "integral term for e1", "", &armConfig::left_e1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_e1_i", "double", 0, "integral term for e1", "", &armConfig::left_e1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w0_i = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_i", "double", 0, "integral term for w0", "", &armConfig::left_w0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w0_i", "double", 0, "integral term for w0", "", &armConfig::left_w0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w1_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_i", "double", 0, "integral term for w1", "", &armConfig::left_w1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w1_i", "double", 0, "integral term for w1", "", &armConfig::left_w1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w2_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w2_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w2_i = 0.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_i", "double", 0, "integral term for w2", "", &armConfig::left_w2_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("left_w2_i", "double", 0, "integral term for w2", "", &armConfig::left_w2_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s0_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_i", "double", 0, "integral term for s0", "", &armConfig::right_s0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s0_i", "double", 0, "integral term for s0", "", &armConfig::right_s0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s1_i = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_i", "double", 0, "integral term for s1", "", &armConfig::right_s1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_s1_i", "double", 0, "integral term for s1", "", &armConfig::right_s1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e0_i = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_i", "double", 0, "integral term for e0", "", &armConfig::right_e0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e0_i", "double", 0, "integral term for e0", "", &armConfig::right_e0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e1_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_i", "double", 0, "integral term for e1", "", &armConfig::right_e1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_e1_i", "double", 0, "integral term for e1", "", &armConfig::right_e1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w0_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w0_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w0_i = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_i", "double", 0, "integral term for w0", "", &armConfig::right_w0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w0_i", "double", 0, "integral term for w0", "", &armConfig::right_w0_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w1_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w1_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w1_i = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_i", "double", 0, "integral term for w1", "", &armConfig::right_w1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w1_i", "double", 0, "integral term for w1", "", &armConfig::right_w1_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w2_i = -100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w2_i = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w2_i = 0.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_i", "double", 0, "integral term for w2", "", &armConfig::right_w2_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(armConfig::AbstractParamDescriptionConstPtr(new armConfig::ParamDescription<double>("right_w2_i", "double", 0, "integral term for w2", "", &armConfig::right_w2_i)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(armConfig::AbstractGroupDescriptionConstPtr(new armConfig::GroupDescription<armConfig::DEFAULT, armConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<armConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<armConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<armConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    armConfig __max__;
    armConfig __min__;
    armConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const armConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static armConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &armConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const armConfig &armConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const armConfig &armConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const armConfig &armConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<armConfig::AbstractParamDescriptionConstPtr> &armConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<armConfig::AbstractGroupDescriptionConstPtr> &armConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const armConfigStatics *armConfig::__get_statics__()
  {
    const static armConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = armConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __ARMRECONFIGURATOR_H__
