// Generated by gencpp from file jerky_mov/move_arm_jointsGoal.msg
// DO NOT EDIT!


#ifndef JERKY_MOV_MESSAGE_MOVE_ARM_JOINTSGOAL_H
#define JERKY_MOV_MESSAGE_MOVE_ARM_JOINTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace jerky_mov
{
template <class ContainerAllocator>
struct move_arm_jointsGoal_
{
  typedef move_arm_jointsGoal_<ContainerAllocator> Type;

  move_arm_jointsGoal_()
    : joints()
    , type(0)
    , wait(false)  {
    }
  move_arm_jointsGoal_(const ContainerAllocator& _alloc)
    : joints(_alloc)
    , type(0)
    , wait(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::JointState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::JointState_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;

   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _wait_type;
  _wait_type wait;




  typedef boost::shared_ptr< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct move_arm_jointsGoal_

typedef ::jerky_mov::move_arm_jointsGoal_<std::allocator<void> > move_arm_jointsGoal;

typedef boost::shared_ptr< ::jerky_mov::move_arm_jointsGoal > move_arm_jointsGoalPtr;
typedef boost::shared_ptr< ::jerky_mov::move_arm_jointsGoal const> move_arm_jointsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jerky_mov

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'jerky_mov': ['/home/rhomni/bax_ws/bax_local/devel/.private/jerky_mov/share/jerky_mov/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "298cc92a24d31028fd232a9184a416b7";
  }

  static const char* value(const ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x298cc92a24d31028ULL;
  static const uint64_t static_value2 = 0xfd232a9184a416b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jerky_mov/move_arm_jointsGoal";
  }

  static const char* value(const ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
sensor_msgs/JointState[] joints\n\
uint8 type\n\
bool wait\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
      stream.next(m.type);
      stream.next(m.wait);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct move_arm_jointsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jerky_mov::move_arm_jointsGoal_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JERKY_MOV_MESSAGE_MOVE_ARM_JOINTSGOAL_H
